---
title: Voeg een sprite toe uit de sprite-bibliotheek
hero_image: images/banner.png
description: Voeg een sprite toe uit de sprite-bibliotheek
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Voeg een sprite toe uit de sprite-bibliotheek
