title: Add a Scratch sprite from the Library
hero_image: images/banner.png
description: Add a Scratch sprite from the Library
original url:
theme: 
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Add a sprite
