title: Add a sprite from the Sprite Library
hero_image: images/banner.png
description: Add a sprite from the Sprite Library
original url:
theme: 
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Add a sprite from the Sprite Library
