---
title: लाइब्रेरी से Scratch स्प्राइट शामिल करना
hero_image: images/banner.png
description: लाइब्रेरी से Scratch स्प्राइट जोड़ना
original url:
theme:
duration: 0
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: स्प्राइट जोड़े
