---
title: গ্রন্থাগার থেকে একটি scratch sprite যুক্ত করা হচ্ছে
hero_image: images/banner.png
description: গ্রন্থাগার থেকে একটি scratch sprite যুক্ত করা হচ্ছে
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: একটি sprite যোগ করুন
