---
title: நூலகத்திலிருந்து ஒரு Scratch sprite-ஐச் சேர்த்தல்
hero_image: படங்கள் / banner.png
description: நூலகத்திலிருந்து ஒரு Scratch sprite-ஐச் சேர்க்கவும்
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: ஒரு sprite-ஐச் சேர்த்தல்
