---
title: Legge til en Scratch-figur fra biblioteket
hero_image: images/banner.png
description: Legge til en Scratch-figur fra biblioteket
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Legg til en figur
