---
title: Faka isprite esivela kwiThala leziSprite
hero_image: images/banner.png
description: Faka isprite esivela kwiThala leziSprite
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Faka isprite esivela kwiThala leziSprite
