---
title: Tilføjelse af en Scratch-sprite fra biblioteket
hero_image: images/banner.png
description: Tilføjelse af en Scratch-sprite fra biblioteket
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Tilføj en sprite
