---
title: Adicionar um actor do Scratch a partir da Biblioteca
hero_image: images/banner.png
description: Adicionar um actor do Scratch a partir da Biblioteca
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adicionar um actor
