---
title: 添加一个库中的Scratch角色
hero_image: images/banner.png
description: 添加一个库中的Scratch角色
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: 添加角色
