---
title: Dodaj lika iz knjižnice likova
hero_image: images/banner.png
description: Dodaj lika iz knjižnice likova
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj lika iz knjižnice likova
