---
title: Scratch-hahmon lisääminen kirjastosta
hero_image: images/banner.png
description: Scratch-hahmon lisääminen kirjastosta
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Lisää hahmo
