---
title: Pagdaragdag ng Scratch sprite mula sa Library
hero_image: mga imahe / banner.png
description: Pagdaragdag ng Scratch sprite mula sa Library
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Magdagdag ng isang sprite
