---
title: Añadir un objeto de Scratch de la biblioteca
hero_image: images / banner.png
description: Añadir un objeto de Scratch de la biblioteca
original url: ""
theme: cc-prototype
duration: 1
curriculum: ""
listed: false
copyedit: true
ingredient: true
interests: ""
technologies: "scratch"
steps:
  - title: Añade un objeto
