---
title: Ychwanegu corlun Scratch o'r Llyfrgell
hero_image: images/banner.png
description: Ychwanegu corlun Scratch o'r Llyfrgell
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ychwanegu corlun
