---
title: Eine Scratch-Figur aus der Bibliothek hinzufügen
hero_image: images/banner.png
description: Eine Scratch-Figur aus der Bibliothek hinzufügen
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Eine Figur hinzufügen
