---
title: Adăugarea unui personaj Scratch din Bibliotecă
hero_image: images/banner.png
description: Adaugă un personaj Scratch din Bibliotecă
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adaugă un personaj
