---
title: Adicione um ator da Biblioteca de Atores
hero_image: images/banner.png
description: Adicione um ator da Biblioteca de Atores
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adicione um ator da Biblioteca de Atores
