---
title: Adicionando um ator Scratch da biblioteca
hero_image: images/banner.png
description: Adicionando um ator Scratch da biblioteca
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Adicione um ator
