---
title: Add a sprite from the Sprite Library
hero_image: છબીઓ / banner.png
description: Add a sprite from the Sprite Library
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "શરૂઆતથી"
steps:
  - 
    title: Add a sprite from the Sprite Library
