---
title: Afegir un personatge de Scratch de la Biblioteca
hero_image: images/banner.png
description: Afegir un personatge de Scratch de la Biblioteca
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Afegir un personatge
