---
title: Dodajanje Scratch figure iz knjižnice
hero_image: images / banner.png
description: Dodajanje Scratch figure iz knjižnice
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj figuro
