---
title: Vyber si postavičku z výběru
hero_image: images/banner.png
description: Vyber si postavičku z výběru
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Vyber si postavičku z výběru
