---
title: ಗ್ರಂಥಾಲಯದಿಂದ ಸ್ಕ್ರ್ಯಾಚ್ ಸ್ಪ್ರೈಟ್ ಅನ್ನು ಸೇರಿಸಲಾಗುತ್ತಿದೆ
hero_image: images/banner.png
description: ಗ್ರಂಥಾಲಯದಿಂದ ಸ್ಕ್ರ್ಯಾಚ್ ಸ್ಪ್ರೈಟ್ ಅನ್ನು ಸೇರಿಸಲಾಗುತ್ತಿದೆ
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: ಸ್ಪ್ರೈಟ್ ಸೇರಿಸಿ
