---
title: Añadir un objeto de Scratch desde la biblioteca
hero_image: images/banner.png
description: Añadir un objeto de Scratch desde la biblioteca
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Añade un objeto
