---
title: Añadir un objeto desde la biblioteca de Scratch
hero_image: images/banner.png
description: Añadir un objeto desde la biblioteca de Scratch
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Añadir un objeto desde la biblioteca de Scratch
