---
title: Scratchi spraidi lisamine teegist
hero_image: images/banner.png
description: Scratchi spraidi lisamine teegist
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Lisa sprait
