---
title: Dodanie duszka Scratcha z biblioteki
hero_image: images / banner.png
description: Dodanie duszka Scratcha z biblioteki
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Dodaj duszka
