---
title: Dodanie duszka z biblioteki Scratch
hero_image: images/banner.png
description: Dodanie duszka z biblioteki Scratch
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Dodaj duszka
