---
title: Pridanie Scratch postavy z knižnice
hero_image: images / banner.png
description: Pridanie Scratch postavy z knižnice
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Pridaj postavu
