---
title: Att lägga till en Scratch sprajt från biblioteket
hero_image: images/banner.png
description: Att lägga till en Scratch sprajt från biblioteket
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Lägga till en sprajt
