---
title: Lägga till en sprajt från Sprajtbiblioteket
hero_image: images/banner.png
description: Lägga till en sprajt från Sprajtbiblioteket
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Lägga till en sprajt från Sprajtbiblioteket
