---
title: লাইব্রেরী থেকে একটি স্ক্র্যাচ স্প্রাইট যোগ করা
hero_image: images/banner.png
description: লাইব্রেরী থেকে একটি স্ক্র্যাচ স্প্রাইট যোগ করা
original url:
theme:
duration: 0
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: scratch
steps:
  - title: একটি স্প্রাইট যোগ করুন
