---
title: Προσθέτοντας ένα αντικείμενο Scratch από τη Βιβλιοθήκη
hero_image: images/banner.png
description: Προσθέτοντας ένα αντικείμενο (sprite) από τη Βιβλιοθήκη του Scratch
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Προσθέτοντας ένα αντικείμενο (sprite) από τη Βιβλιοθήκη του Scratch
