---
title: Ajout d'un lutin depuis la bibliothèque
hero_image: images/banner.png
description: Ajout d'un lutin depuis la bibliothèque
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - title: Ajouter un lutin
