---
title: Ajouter un sprite depuis la bibliothèque de sprites
hero_image: images/banner.png
description: Ajouter un sprite depuis la bibliothèque de sprites
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Ajouter un sprite depuis la bibliothèque de sprites
