---
title: Kütüphaneden bir Scratch kuklası ekleme
hero_image: images/banner.png
description: Kütüphaneden bir Scratch kuklası ekleme
original url:
theme:
duration: 1
curriculum:
listed: false
copyedit: false
ingredient: true
interests:
technologies: "scratch"
steps:
  - 
    title: Bir kukla ekle
